name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: "1 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Update
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update Scripts
        id: update
        shell: bash
        run: |
          wget https://greasyfork.org/scripts/431691-bypass-all-shortlinks/code/Bypass%20All%20Shortlinks.user.js
          wget https://greasyfork.org/scripts/443888-additional-bypass/code/Additional%20Bypass.user.js
          wget https://greasyfork.org/scripts/439683-all-popups-blocker-and-recaptcha-solver/code/All%20Popups%20Blocker%20and%20reCAPTCHA%20Solver.user.js
          ls
          git config --global user.email "rushiacc1@protonmail.com"
          git config --global user.name "motoonepower"
          git config --global color.ui true
          git status && git add . && git commit -m "Update Scripts Daily on $(date -u +"%D %T%p")" && git push
