name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: "1 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update Scripts
        id: update
        shell: bash
        run: |
          wget https://greasyfork.org/scripts/431691-bypass-all-shortlinks/code/Bypass%20All%20Shortlinks.user.js
          ls
       
